### ISSUE TITLE
NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by CAI23sbP** [weixians/esa#2]
How are you @weixians ?
I have some issue about your code.
When i run `run_dqn.py`. there is a issue [`NaN or Inf found in input tensor.`]
Here is figure
![image](https://github.com/weixians/esa/assets/108871750/3682a98e-a872-4df1-9e26-6442306ea263)

**Comment by ponder-lxl** [comment]
Hello, have you resolved this issue? If it's resolved, I hope you can let me know. Thank you

**Comment by CAI23sbP** [comment]
How are you @XinLei-L.
I am so sorry... i am still in this issue.

**Comment by ponder-lxl** [comment]
I have trained on this project, and this situation has no impact on the training。

> How are you @XinLei-L. I am so sorry... i am still in this issue.

**Comment by CAI23sbP** [comment]
@XinLei-L oh okay!
Thanks!
